version: '3'

networks: 
  fullcycle:
    driver: bridge

services:
  docker_nginx:
    build: .
    ports:
      - '3000:3000'
    networks:
      - fullcycle
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fullcycle
    ports:
      - "3306:3306"
    networks:
      - fullcycle

  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - fullcycle
    depends_on:
      - docker_nginx
